config/routes.rb
Rails.application.routes.draw do
  root 'people#index'

  resources :organisations do
    resources :memberships, only: [:new, :create, :destroy]
  end
  resources :people

end

app/models/contact_details.rb
class ContactDetails < ActiveRecord::Base
  EMAIL_REGEX = /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/
  ALLOWED_ATTRIBUTES = %i( email telephone address_line_1 address_line_2 address_line_3 city postal_code country_code)

  belongs_to :contactable, polymorphic: true

  validates :email, format: EMAIL_REGEX, allow_blank: true
end

app/models/organisation.rb
class Organisation < ActiveRecord::Base
  has_many :memberships, dependent: :destroy
  has_many :people, through: :memberships

  has_one :contact_details, as: :contactable, dependent: :destroy

  accepts_nested_attributes_for :contact_details
  
  validates :name, presence: true

  def contact_details
    super || build_contact_details
  end
end

app/models/organisation/membership.rb
class Organisation::Membership < ActiveRecord::Base
  belongs_to :organisation
  belongs_to :person
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_one :membership,  class_name: 'Organisation::Membership', dependent: :destroy
  has_one :organisation, through: :membership

  has_one :contact_details, as: :contactable, dependent: :destroy

  accepts_nested_attributes_for :contact_details
  accepts_nested_attributes_for :membership

  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    [first_name, last_name].join(" ")
  end

  def contact_details *args
    super(*args) || build_contact_details
  end

  def membership *args
    super(*args) || build_membership
  end
end

app/controllers/api/organisations_controller.rb
class Api::OrganisationsController < ApplicationController
  
  def index
    @organisations = Organisation.all
  end

  def new
    @organisation = Organisation.new
  end

  def create
    @organisation = Organisation.create(organisation_params)
    if @organisation.save
      redirect_to @organisation
    else
      render :new
    end
  end

  def show
    @organisation = Organisation.find(id: params[:id])
  end

  def edit
    @organisation = Organisation.find(id: params[:id])
    @organisation.update(organisation_params)
    if @organisation.save
      redirect_to @organisation
    else
      render :edit
    end
  end

  private

  def organisation_params
    params.require(:organisation).permit(:name)
  end

end

app/controllers/api/people_controller.rb
class Api::PeopleController < ApplicationController
  
  def index
    @people = Person.all
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.create(person_params)
    if @person.save
      redirect_to @person
    else
      render :new
    end
  end

  def show
    @person = Person.find(id: params[:id])
  end

  def edit
    @person = Person.find(id: params[:id])
    @person.update(person_params)
    if @person.save
      redirect_to @person
    else
      render :edit
    end
  end

  private

  def person_params
    params.require(:person).permit(:first_name, :second_name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/frontend_controller.rb
class FrontendController
  def show
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController

  def new
    @membership = organisation.memberships.build
  end

  def create
    if organisation.memberships.create(membership_params)
      redirect_to organisation_path(@organisation)
    else
      flash[:error] = "Unable to create membership"
      render :new
    end
    
  end

  def destroy
    membership = organisation.memberships.where(id: params[:id]).first
    unless membership.destroy
      flash[:error] = "Error deleting membership"
    end
    redirect_to organisation
  end

  def people_options
    Person
      .where.not(id: organisation.memberships.select(:person_id))
      .select(:first_name, :last_name, :id)
      .map { |p| [ p.full_name, p.id ] }
  end
  helper_method :people_options

  private

  def organisation
    @organisation ||= Organisation.find(params[:organisation_id])
  end

  def membership_params
    params.require(:organisation_membership).permit(:person_id)
  end

end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  
  def index
    @organisations = Organisation.all
  end

  def new
    @organisation = Organisation.new
  end

  def create
    @organisation = Organisation.create(organisation_params)
    if @organisation.save
      redirect_to @organisation
    else
      flash.now[:error] = @organisation.errors.full_messages.to_sentence
      render :new
    end
  end

  def show
    org_by_id
  end

  def edit
    org_by_id
  end

  def update
    org_by_id.update(organisation_params)
    if @organisation.save
      redirect_to @organisation
    else
      flash.now[:error] = @organisation.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if org_by_id.destroy
      flash[:success] = "Organisation successfully deleted"
    else
      flash[:error] = "Cannot delete organisation"
    end
    redirect_to action: :index
  end

  private

  def org_by_id
    @organisation = Organisation.find(params[:id])
  end

  def organisation_params
    params.require(:organisation).permit(:name, contact_details_attributes: ContactDetails::ALLOWED_ATTRIBUTES)
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  
  def index
    @people = Person.all
  end

  def new
    @person = Person.new
    @person.membership.organisation_id = params[:organisation_id]
  end

  def create
    @person = Person.create(person_params)
    if @person.membership.organisation_id.nil?
      @person.membership = nil
    end
    if @person.save
      redirect_to @person
    else
      flash.now[:error] = @person.errors.full_messages.to_sentence
      render :new
    end
  end

  def show
    person_by_id
  end

  def edit
    person_by_id
  end

  def update
    person_by_id.update(person_params)
    if @person.membership.organisation_id.nil?
      @person.membership = nil
    end
    if @person.save
      redirect_to @person
    else
      flash.now[:error] = @person.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if person_by_id.destroy
      flash[:success] = "Person successfully deleted"
    else
      flash[:error] = "Cannot delete person"
    end
    redirect_to action: :index
  end

  def organisation_options
    Organisation.pluck(:name, :id)
  end
  helper_method :organisation_options

  private

  def person_by_id
    @person ||= Person.find(params[:id])
  end

  def person_params
    params.require(:person)
      .permit(
        :first_name,
        :last_name,
        contact_details_attributes: ContactDetails::ALLOWED_ATTRIBUTES,
        membership_attributes: [:organisation_id]
      )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_class path
    'active' if current_page?(path)
  end

  def bootstrap_class_for type
    case type
    when 'success' then 'alert-success'
    when 'error'   then 'alert-danger'
    when 'alert'   then 'alert-warning'
    when 'notive'  then 'alert-info'
    else type
    end
  end
end

app/views/application/_contact_details.slim
.panel
  .panel-body
    .container
      - { email: "Email", \
          telephone: "Telephone", \
          address_line_1: "House name/number", \
          address_line_2: "Street", \
          address_link_3: "Area", \
          city: "City", \
          postal_code: "Postcode", \
          country_code: "Country" \
        }.each do |attr, name|
        .row
          .col-sm-3= "#{name}:"
          .col-sm-5= details[attr]

app/views/application/_contact_details_form.slim
.form_group
 = f.label :email, class: 'col-sm-2'
 .col-sm-10
   = f.email_field :email, class: 'form-control'
.form_group
 = f.label :telephone, class: 'col-sm-2'
 .col-sm-10
   = f.telephone_field :telephone, class: 'form-control'
.form_group
 = f.label :address, class: 'col-sm-2'
 .col-sm-10
   = f.text_field :address_line_1, class: 'form-control', placeholder: 'House name or number'
   = f.text_field :address_line_2, class: 'form-control', placeholder: 'Street name'
   = f.text_field :address_line_3, class: 'form-control'
   = f.text_field :city, class: 'form-control', placeholder: 'City'
   = f.text_field :postal_code, class: 'form-control', placeholder: 'Postcode'
   = f.country_select :country_code, class: 'form-control'

app/views/application/_flash_messages.slim
- flash.each do |type, message|
  .alert.fade.in class=bootstrap_class_for(type)
    = message

app/views/layouts/application.slim
doctype html
html
  head
    title Address Book
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    nav.navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          button.navbar-toggle.collapsed data-toggle="collapse" data-target="#navbar-menu"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="/" Address Book

        .collapse.navbar-collapse#navbar-menu
          ul.nav.navbar-nav
            li class=active_class(people_path)
              = link_to "People", people_path
            li class=active_class(organisations_path)
              = link_to "Organisations", organisations_path 


    .container
      = render 'flash_messages', flash: flash
      == yield

app/views/memberships/new.slim
h1= "Add person to #{@organisation.name}"

= form_for @membership, html: { class: 'form-horizontal' } do |f|
  .form_group
    = f.label :person, class: 'col-sm-2'
    .col-sm-10
      = f.select :person_id, people_options

  .form_group
    .col-sm-10
      = f.submit nil, class: 'btn btn-default'
      = link_to :cancel, organisation_path(@organisation), class: 'btn btn-default'

app/views/organisations/_form.slim
= form_for @organisation, html: { class: 'form-horizontal' } do |f|
  .form_group
    = f.label :name, class: 'col-sm-2'
    .col-sm-10
      = f.text_field :name, placeholder: "Company name", class: 'form-control'
  .form_group
    = f.fields_for :contact_details, @organisation.contact_details do |builder|
      = render 'contact_details_form', f: builder

  .form_group
    .col-sm-10
      = f.submit nil, class: 'btn btn-default'
      = link_to :cancel, :back, class: 'btn btn-default'

app/views/organisations/edit.slim
h1 Edit Organisation

= render 'form'

app/views/organisations/index.slim
.panel.panel-default
  .panel-heading Organisations

  table.table
    - if @organisations.empty?
      p You have no organisations yet
    - else 
      - @organisations.each do |organisation|
        tr
          td= link_to organisation.name, organisation_path(organisation)
          td.action
            = link_to edit_organisation_path(organisation) do
              i.glyphicon.glyphicon-pencil
          td.action
            = link_to organisation_path(organisation), method: :delete, data: { confirm: "Are you sure?" } do
              i.glyphicon.glyphicon-remove

  .panel-footer
    =link_to :add, new_organisation_path

app/views/organisations/new.slim
h1 Add Organisation

= render 'form'

app/views/organisations/show.slim
h1= @organisation.name
= link_to :edit, edit_organisation_path(@organisation), class: 'btn btn-default'
= link_to :delete, organisation_path(@organisation), method: :delete, class: 'btn btn-default', data: { confirm: 'Are you sure?' }

= render 'contact_details', details: @organisation.contact_details

h3 People
- if @organisation.memberships.any?
  table.table
    - @organisation.memberships.includes(:person).each do |membership|
     tr
       td=link_to membership.person.full_name, person_path(membership.person)
       td=link_to organisation_membership_path(@organisation, membership.id), method: :delete, data: { confirm: "Are you sure?" } do
         .glyphicon.glyphicon-remove
- else
  No people in this organisation yet

p
  = link_to "Add person", new_organisation_membership_path(organisation_id: @organisation.id), class: 'btn btn-default'
  = link_to "Create person", new_person_path(organisation_id: @organisation.id), class: 'btn btn-default'
  

app/views/people/_form.slim
= form_for @person, html: { class: 'form-horizontal' } do |f|
  .form_group
    = f.label :name, class: 'col-sm-2'
    .col-sm-5
      = f.text_field :first_name, placeholder: "Jane", class: 'form-control'
    .col-sm-5
      = f.text_field :last_name, placeholder: "Doe", class: 'form-control'
  .form_group
    = f.fields_for :contact_details, @person.contact_details do |builder|
      = render 'contact_details_form', f: builder

  .form_group
    = f.fields_for :membership, @person.membership do |builder|
      = builder.label :organisation, class: 'col-sm-2'
      .col-sm-10
        = builder.select :organisation_id, organisation_options, include_blank: 'None', class: 'form-control'

  .form_group
    .col-sm-10
      = f.submit nil, class: 'btn btn-default'
      = link_to :cancel, :back, class: 'btn btn-default'

app/views/people/edit.slim
h1 Edit Person

= render 'form'

app/views/people/index.slim
.panel.panel-default
  .panel-heading People

  table.table
    - if @people.empty?
      p You have no people yet
    - else 
      - @people.each do |person|
        tr
          td= link_to person.full_name, person_path(person)
          td.action
            = link_to edit_person_path(person) do
              i.glyphicon.glyphicon-pencil
          td.action
            = link_to person_path(person), method: :delete, data: { confirm: "Are you sure?" } do
              i.glyphicon.glyphicon-remove

  .panel-footer
    =link_to :add, new_person_path

app/views/people/new.slim
h1 Add Person

= render 'form'

app/views/people/show.slim
h1= @person.full_name
= link_to :edit, edit_person_path(@person), class: 'btn btn-default'
= link_to :delete, person_path(@person), method: :delete, class: 'btn btn-default', data: { confirm: "Are you sure?" }

- if @person.contact_details.persisted?
  h3 Contact Details
  = render 'contact_details', details: @person.contact_details

- if @person.membership.persisted?
  h3 Organisation
  = link_to @person.organisation.name, organisation_path(@person.organisation)